name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        Please search existing issues before creating a new one.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/Bright-L01/proof-sketcher/blob/main/CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have included all relevant information below
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: lean-file
    attributes:
      label: Lean file (if applicable)
      description: Please paste the Lean file that triggered the issue
      render: lean
      placeholder: |
        -- Paste your Lean code here
        theorem example : 2 + 2 = 4 := by norm_num

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Parser (Lean file parsing)
        - Generator (AI explanation generation)
        - Animator (Manim animation creation)
        - Exporter (HTML/Markdown/PDF export)
        - CLI (Command line interface)
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
      value: |
        - OS: [e.g. macOS 13.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g. 3.11.5]
        - Proof Sketcher version: [e.g. 0.1.0]
        - Lean version: [e.g. 4.3.0]
        - Claude CLI version: [run `claude --version`]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Screenshots, links to related issues, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to contribute a fix?
      options:
        - label: I'm willing to contribute a fix for this issue
          required: false